// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tests/test space1/test 1.proto

package protobufel1.test1;

public final class Test1 {
  private Test1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Message111OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobufel1.test1.Message111)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string field1 = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getField1List();
    /**
     * <code>repeated string field1 = 1;</code>
     */
    int getField1Count();
    /**
     * <code>repeated string field1 = 1;</code>
     */
    java.lang.String getField1(int index);
    /**
     * <code>repeated string field1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getField1Bytes(int index);
  }
  /**
   * Protobuf type {@code protobufel1.test1.Message111}
   */
  public static final class Message111 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobufel1.test1.Message111)
      Message111OrBuilder {
    // Use Message111.newBuilder() to construct.
    private Message111(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message111(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message111 defaultInstance;
    public static Message111 getDefaultInstance() {
      return defaultInstance;
    }

    public Message111 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message111(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                field1_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              field1_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          field1_ = field1_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobufel1.test1.Test1.internal_static_protobufel1_test1_Message111_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobufel1.test1.Test1.internal_static_protobufel1_test1_Message111_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobufel1.test1.Test1.Message111.class, protobufel1.test1.Test1.Message111.Builder.class);
    }

    public static com.google.protobuf.Parser<Message111> PARSER =
        new com.google.protobuf.AbstractParser<Message111>() {
      public Message111 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message111(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message111> getParserForType() {
      return PARSER;
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList field1_;
    /**
     * <code>repeated string field1 = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getField1List() {
      return field1_;
    }
    /**
     * <code>repeated string field1 = 1;</code>
     */
    public int getField1Count() {
      return field1_.size();
    }
    /**
     * <code>repeated string field1 = 1;</code>
     */
    public java.lang.String getField1(int index) {
      return field1_.get(index);
    }
    /**
     * <code>repeated string field1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getField1Bytes(int index) {
      return field1_.getByteString(index);
    }

    private void initFields() {
      field1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < field1_.size(); i++) {
        output.writeBytes(1, field1_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < field1_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(field1_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getField1List().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobufel1.test1.Test1.Message111 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufel1.test1.Test1.Message111 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufel1.test1.Test1.Message111 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufel1.test1.Test1.Message111 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufel1.test1.Test1.Message111 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobufel1.test1.Test1.Message111 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobufel1.test1.Test1.Message111 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobufel1.test1.Test1.Message111 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobufel1.test1.Test1.Message111 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobufel1.test1.Test1.Message111 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobufel1.test1.Test1.Message111 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobufel1.test1.Message111}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobufel1.test1.Message111)
        protobufel1.test1.Test1.Message111OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobufel1.test1.Test1.internal_static_protobufel1_test1_Message111_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobufel1.test1.Test1.internal_static_protobufel1_test1_Message111_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobufel1.test1.Test1.Message111.class, protobufel1.test1.Test1.Message111.Builder.class);
      }

      // Construct using protobufel1.test1.Test1.Message111.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        field1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobufel1.test1.Test1.internal_static_protobufel1_test1_Message111_descriptor;
      }

      public protobufel1.test1.Test1.Message111 getDefaultInstanceForType() {
        return protobufel1.test1.Test1.Message111.getDefaultInstance();
      }

      public protobufel1.test1.Test1.Message111 build() {
        protobufel1.test1.Test1.Message111 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobufel1.test1.Test1.Message111 buildPartial() {
        protobufel1.test1.Test1.Message111 result = new protobufel1.test1.Test1.Message111(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          field1_ = field1_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.field1_ = field1_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobufel1.test1.Test1.Message111) {
          return mergeFrom((protobufel1.test1.Test1.Message111)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobufel1.test1.Test1.Message111 other) {
        if (other == protobufel1.test1.Test1.Message111.getDefaultInstance()) return this;
        if (!other.field1_.isEmpty()) {
          if (field1_.isEmpty()) {
            field1_ = other.field1_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureField1IsMutable();
            field1_.addAll(other.field1_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobufel1.test1.Test1.Message111 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobufel1.test1.Test1.Message111) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList field1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureField1IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          field1_ = new com.google.protobuf.LazyStringArrayList(field1_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getField1List() {
        return field1_.getUnmodifiableView();
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public int getField1Count() {
        return field1_.size();
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public java.lang.String getField1(int index) {
        return field1_.get(index);
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getField1Bytes(int index) {
        return field1_.getByteString(index);
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public Builder setField1(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureField1IsMutable();
        field1_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public Builder addField1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureField1IsMutable();
        field1_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public Builder addAllField1(
          java.lang.Iterable<java.lang.String> values) {
        ensureField1IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, field1_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public Builder clearField1() {
        field1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field1 = 1;</code>
       */
      public Builder addField1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureField1IsMutable();
        field1_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobufel1.test1.Message111)
    }

    static {
      defaultInstance = new Message111(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobufel1.test1.Message111)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufel1_test1_Message111_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufel1_test1_Message111_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036tests/test space1/test 1.proto\022\021protob" +
      "ufel1.test1\"\034\n\nMessage111\022\016\n\006field1\030\001 \003(" +
      "\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobufel1_test1_Message111_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobufel1_test1_Message111_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobufel1_test1_Message111_descriptor,
        new java.lang.String[] { "Field1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
