// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageWithBytes1.proto

package com.fictional.test;

public final class MessageWithBytes1Proto {
  private MessageWithBytes1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageWithBytes1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:ognl.test.proto.MessageWithBytes1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes bytes = 1;</code>
     */
    boolean hasBytes();
    /**
     * <code>required bytes bytes = 1;</code>
     */
    com.google.protobuf.ByteString getBytes();
  }
  /**
   * Protobuf type {@code ognl.test.proto.MessageWithBytes1}
   */
  public static final class MessageWithBytes1 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ognl.test.proto.MessageWithBytes1)
      MessageWithBytes1OrBuilder {
    // Use MessageWithBytes1.newBuilder() to construct.
    private MessageWithBytes1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageWithBytes1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageWithBytes1 defaultInstance;
    public static MessageWithBytes1 getDefaultInstance() {
      return defaultInstance;
    }

    public MessageWithBytes1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageWithBytes1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              bytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fictional.test.MessageWithBytes1Proto.internal_static_ognl_test_proto_MessageWithBytes1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fictional.test.MessageWithBytes1Proto.internal_static_ognl_test_proto_MessageWithBytes1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1.class, com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageWithBytes1> PARSER =
        new com.google.protobuf.AbstractParser<MessageWithBytes1>() {
      public MessageWithBytes1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageWithBytes1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageWithBytes1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>required bytes bytes = 1;</code>
     */
    public boolean hasBytes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes bytes = 1;</code>
     */
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    private void initFields() {
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, bytes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, bytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ognl.test.proto.MessageWithBytes1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ognl.test.proto.MessageWithBytes1)
        com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fictional.test.MessageWithBytes1Proto.internal_static_ognl_test_proto_MessageWithBytes1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fictional.test.MessageWithBytes1Proto.internal_static_ognl_test_proto_MessageWithBytes1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1.class, com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1.Builder.class);
      }

      // Construct using com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fictional.test.MessageWithBytes1Proto.internal_static_ognl_test_proto_MessageWithBytes1_descriptor;
      }

      public com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 getDefaultInstanceForType() {
        return com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1.getDefaultInstance();
      }

      public com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 build() {
        com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 buildPartial() {
        com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 result = new com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bytes_ = bytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1) {
          return mergeFrom((com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 other) {
        if (other == com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1.getDefaultInstance()) return this;
        if (other.hasBytes()) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBytes()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fictional.test.MessageWithBytes1Proto.MessageWithBytes1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bytes = 1;</code>
       */
      public boolean hasBytes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes bytes = 1;</code>
       */
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>required bytes bytes = 1;</code>
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bytes = 1;</code>
       */
      public Builder clearBytes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ognl.test.proto.MessageWithBytes1)
    }

    static {
      defaultInstance = new MessageWithBytes1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ognl.test.proto.MessageWithBytes1)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ognl_test_proto_MessageWithBytes1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ognl_test_proto_MessageWithBytes1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027messageWithBytes1.proto\022\017ognl.test.pro" +
      "to\"\"\n\021MessageWithBytes1\022\r\n\005bytes\030\001 \002(\014B," +
      "\n\022com.fictional.testB\026MessageWithBytes1P" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ognl_test_proto_MessageWithBytes1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ognl_test_proto_MessageWithBytes1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ognl_test_proto_MessageWithBytes1_descriptor,
        new java.lang.String[] { "Bytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
