// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subMessageStandaloneOne.proto

package com.fictional.test;

public final class SubMessageStandaloneOneProto {
  private SubMessageStandaloneOneProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SubMessageStandaloneOneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ognl.test.proto.SubMessageStandaloneOne)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
     */
    com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage getMsg();
    /**
     * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
     */
    com.fictional.test.SubMessageStandaloneOneProto.SimpleMessageOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code ognl.test.proto.SubMessageStandaloneOne}
   */
  public static final class SubMessageStandaloneOne extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ognl.test.proto.SubMessageStandaloneOne)
      SubMessageStandaloneOneOrBuilder {
    // Use SubMessageStandaloneOne.newBuilder() to construct.
    private SubMessageStandaloneOne(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SubMessageStandaloneOne(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SubMessageStandaloneOne defaultInstance;
    public static SubMessageStandaloneOne getDefaultInstance() {
      return defaultInstance;
    }

    public SubMessageStandaloneOne getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SubMessageStandaloneOne(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SubMessageStandaloneOne_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SubMessageStandaloneOne_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne.class, com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne.Builder.class);
    }

    public static com.google.protobuf.Parser<SubMessageStandaloneOne> PARSER =
        new com.google.protobuf.AbstractParser<SubMessageStandaloneOne>() {
      public SubMessageStandaloneOne parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubMessageStandaloneOne(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SubMessageStandaloneOne> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSG_FIELD_NUMBER = 1;
    private com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage msg_;
    /**
     * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
     */
    public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage getMsg() {
      return msg_;
    }
    /**
     * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
     */
    public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessageOrBuilder getMsgOrBuilder() {
      return msg_;
    }

    private void initFields() {
      msg_ = com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMsg().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, msg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ognl.test.proto.SubMessageStandaloneOne}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ognl.test.proto.SubMessageStandaloneOne)
        com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SubMessageStandaloneOne_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SubMessageStandaloneOne_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne.class, com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne.Builder.class);
      }

      // Construct using com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.getDefaultInstance();
        } else {
          msgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SubMessageStandaloneOne_descriptor;
      }

      public com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne getDefaultInstanceForType() {
        return com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne.getDefaultInstance();
      }

      public com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne build() {
        com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne buildPartial() {
        com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne result = new com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne) {
          return mergeFrom((com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne other) {
        if (other == com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsg()) {
          
          return false;
        }
        if (!getMsg().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fictional.test.SubMessageStandaloneOneProto.SubMessageStandaloneOne) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage msg_ = com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessageOrBuilder> msgBuilder_;
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage getMsg() {
        if (msgBuilder_ == null) {
          return msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public Builder setMsg(com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public Builder setMsg(
          com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public Builder mergeMsg(com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage value) {
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              msg_ != com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.getDefaultInstance()) {
            msg_ =
              com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.getDefaultInstance();
          onChanged();
        } else {
          msgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder getMsgBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessageOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_;
        }
      }
      /**
       * <code>required .ognl.test.proto.SimpleMessage msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessageOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessageOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ognl.test.proto.SubMessageStandaloneOne)
    }

    static {
      defaultInstance = new SubMessageStandaloneOne(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ognl.test.proto.SubMessageStandaloneOne)
  }

  public interface SimpleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ognl.test.proto.SimpleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code ognl.test.proto.SimpleMessage}
   */
  public static final class SimpleMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ognl.test.proto.SimpleMessage)
      SimpleMessageOrBuilder {
    // Use SimpleMessage.newBuilder() to construct.
    private SimpleMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SimpleMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SimpleMessage defaultInstance;
    public static SimpleMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SimpleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SimpleMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SimpleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.class, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SimpleMessage> PARSER =
        new com.google.protobuf.AbstractParser<SimpleMessage>() {
      public SimpleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ognl.test.proto.SimpleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ognl.test.proto.SimpleMessage)
        com.fictional.test.SubMessageStandaloneOneProto.SimpleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SimpleMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SimpleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.class, com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.Builder.class);
      }

      // Construct using com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fictional.test.SubMessageStandaloneOneProto.internal_static_ognl_test_proto_SimpleMessage_descriptor;
      }

      public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage getDefaultInstanceForType() {
        return com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.getDefaultInstance();
      }

      public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage build() {
        com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage buildPartial() {
        com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage result = new com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage) {
          return mergeFrom((com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage other) {
        if (other == com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fictional.test.SubMessageStandaloneOneProto.SimpleMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ognl.test.proto.SimpleMessage)
    }

    static {
      defaultInstance = new SimpleMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ognl.test.proto.SimpleMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ognl_test_proto_SubMessageStandaloneOne_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ognl_test_proto_SubMessageStandaloneOne_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ognl_test_proto_SimpleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ognl_test_proto_SimpleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035subMessageStandaloneOne.proto\022\017ognl.te" +
      "st.proto\"F\n\027SubMessageStandaloneOne\022+\n\003m" +
      "sg\030\001 \002(\0132\036.ognl.test.proto.SimpleMessage" +
      "\")\n\rSimpleMessage\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 " +
      "\001(\005B2\n\022com.fictional.testB\034SubMessageSta" +
      "ndaloneOneProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ognl_test_proto_SubMessageStandaloneOne_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ognl_test_proto_SubMessageStandaloneOne_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ognl_test_proto_SubMessageStandaloneOne_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_ognl_test_proto_SimpleMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ognl_test_proto_SimpleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ognl_test_proto_SimpleMessage_descriptor,
        new java.lang.String[] { "Name", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
